/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ModelsObjectPageObjectPage journey");

        opaTest("Navigate to ModelsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheModelsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheModelsListGenerated.onTable().iCheckRows();
            When.onTheModelsListGenerated.onTable().iPressRow(0);

            Then.onTheModelsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheModelsObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the FieldGroup::General section of the Object Page", function (_Given, When, Then) {
            When.onTheModelsObjectPageGenerated.iGoToSection({ section: "FieldGroup::General" });
            Then.onTheModelsObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "ModelVersion" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "ModelStatus" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "Brand" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "OEGroup" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "SubGroup" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "Region" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "Country" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "PropulsionType" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "Platform" });
            Then.onTheModelsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "DevelopmentCode" });
        });

        opaTest("Check the BudgetRows::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheModelsObjectPageGenerated.iGoToSection({ section: "BudgetRows::LineItem" });
            Then.onTheModelsObjectPageGenerated.iCheckSection({ section: "BudgetRows::LineItem" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});