/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ModelsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheModelsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheModelsListGenerated.onFilterBar().iCheckFilterField({ property: "Brand" });
            Then.onTheModelsListGenerated.onFilterBar().iCheckFilterField({ property: "Region" });
            Then.onTheModelsListGenerated.onFilterBar().iCheckFilterField({ property: "Country" });
            Then.onTheModelsListGenerated.onFilterBar().iCheckFilterField({ property: "PropulsionType" });
            Then.onTheModelsListGenerated.onFilterBar().iCheckFilterField({ property: "ModelStatus" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheModelsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheModelsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheModelsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheModelsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheModelsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheModelsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Model":{"header":"Model"},"Brand":{"header":"Brand"},"Region":{"header":"Region"},"Country":{"header":"Country"},"PropulsionType":{"header":"Propulsion Type"},"Platform":{"header":"Platform"},"ModelStatus":{"header":"Status"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheModelsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheModelsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheModelsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheModelsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});